# Generated by Django 3.2.10 on 2022-11-06 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InfoProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=250, verbose_name='Product Name')),
                ('description', models.TextField(max_length=250, verbose_name='Descroption')),
                ('price', models.FloatField(max_length=250, verbose_name='Price')),
                ('image', models.ImageField(max_length=250, upload_to='', verbose_name='Image')),
                ('status', models.BooleanField(verbose_name='Status')),
            ],
            options={
                'verbose_name': 'товар',
                'verbose_name_plural': 'товари',
            },
        ),
    ]
